version: 0.0
os: linux # Operating system of the target instances
files:
  - source: / # Root of the artifact (our Node.js app)
    destination: /home/ubuntu/devsecops-app #  Destination on the EC2 instance, changed to ubuntu

hooks:
  ApplicationStop:
    # Stop the Node.js application if it's already running
    - location: scripts/stop_application.sh
      timeout: 60
      runas: ubuntu #  Run as the ubuntu user

  BeforeInstall:
    # Clean up previous deployment, if any
    - location: scripts/before_install.sh
      timeout: 60
      runas: ubuntu #  Run as the ubuntu user

  AfterInstall:
    # Install Node.js dependencies after the application files are copied
    - location: scripts/after_install.sh
      timeout: 120
      runas: ubuntu #  Run as the ubuntu user

  ApplicationStart:
    # Start the Node.js application
    - location: scripts/start_application.sh
      timeout: 60
      runas: ubuntu #  Run as the ubuntu user

  ValidateService:
    # Validate that the application started correctly
    - location: scripts/validate_service.sh
      timeout: 60
      runas: ubuntu #  Run as the ubuntu user