AWSTemplateFormatVersion: '2010-09-09'
Description: CodeDeploy Application and Deployment Groups for DevSecOps Pipeline.

Parameters:
  StagingInstanceTag:
    Type: String
    Default: Staging
    Description: Value of the 'Environment' tag for Staging EC2 instance.
  ProductionInstanceTag:
    Type: String
    Default: Production
    Description: Value of the 'Environment' tag for Production EC2 instance.

Resources:
  # CodeDeploy Application
  NodeJsAppCodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: DevSecOpsNodeJsApp

  # CodeDeploy Deployment Group for Staging
  StagingDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref NodeJsAppCodeDeployApplication
      DeploymentGroupName: DevSecOpsStagingDeploymentGroup
      ServiceRoleArn: !ImportValue DevSecOpsCodeDeployServiceRoleArn
      DeploymentConfigName: CodeDeployDefault.OneAtATime # For basic deployments
      Ec2TagFilters:
        - Key: Environment
          Value: !Ref StagingInstanceTag
          Type: KEY_AND_VALUE
      AutoRollbackConfiguration:
        Enabled: true
        Events:
          - DEPLOYMENT_FAILURE
          - DEPLOYMENT_STOP_ON_ALARM
          - DEPLOYMENT_STOP_ON_REQUEST

  # CodeDeploy Deployment Group for Production
  ProductionDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref NodeJsAppCodeDeployApplication
      DeploymentGroupName: DevSecOpsProductionDeploymentGroup
      ServiceRoleArn: !ImportValue DevSecOpsCodeDeployServiceRoleArn
      DeploymentConfigName: CodeDeployDefault.OneAtATime
      Ec2TagFilters:
        - Key: Environment
          Value: !Ref ProductionInstanceTag
          Type: KEY_AND_VALUE
      AutoRollbackConfiguration:
        Enabled: true
        Events:
          - DEPLOYMENT_FAILURE
          - DEPLOYMENT_STOP_ON_ALARM
          - DEPLOYMENT_STOP_ON_REQUEST

Outputs:
  # Export the Name of the CodeDeploy Application
  CodeDeployApplicationName:
    Description: Name of the CodeDeploy Application
    Value: !Ref NodeJsAppCodeDeployApplication # This references the logical ID
    Export:
      Name: DevSecOpsNodeJsApplicationName # Unique export name

  # Export the Name of the Staging Deployment Group
  CodeDeployStagingDeploymentGroupName:
    Description: Name of the Staging CodeDeploy Deployment Group
    Value: !Ref StagingDeploymentGroup # This references the logical ID
    Export:
      Name: DevSecOpsStagingDeploymentGroupName # Unique export name

  # Export the Name of the Production Deployment Group
  CodeDeployProductionDeploymentGroupName:
    Description: Name of the Production CodeDeploy Deployment Group
    Value: !Ref ProductionDeploymentGroup # This references the logical ID
    Export:
      Name: DevSecOpsProductionDeploymentGroupName # Unique export name