AWSTemplateFormatVersion: '2010-09-09'
Description: CodeDeploy Application and Deployment Group for Lambda Canary Deployments.

Resources:
  # CodeDeploy Application for Lambda
  LambdaCodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: TransactionSimulatorLambdaApp # This is the name referenced by the pipeline

  # CodeDeploy Deployment Group for Lambda Canary Deployment
  LambdaDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref LambdaCodeDeployApplication.ApplicationName
      DeploymentGroupName: TransactionSimulatorLambdaDeploymentGroup # This name will be referenced in CodePipeline
      DeploymentStyle:
        DeploymentType: BLUE_GREEN # Required for Lambda traffic shifting
        DeploymentOption: WITH_TRAFFIC_CONTROL # Required for BLUE_GREEN
      ServiceRoleArn: !GetAtt CodeDeployServiceRole.Arn # CodeDeploy's service role (defined in CodePipeline YAML for now, but should ideally be in its own IAM stack)
      DeploymentConfigName: CodeDeployDefault.LambdaLinear10PercentEvery1Minute # Example: 10% traffic every 1 minute
      # Other options:
      # CodeDeployDefault.LambdaCanary10Percent5Minutes
      # CodeDeployDefault.LambdaAllAtOnce (for immediate full shift)

      # Lambda Function Configuration (Required for CodeDeploy Lambda deployment type)
      # This tells CodeDeploy which Lambda function and aliases it's managing.
      # The properties reference the Lambda function and aliases that Terraform will deploy.
      LambdaFunctionInfoList:
        - FunctionName: TransactionSimulatorAPI # The name of your Lambda function (as defined in Terraform)
          FunctionAlias: LIVE # The alias CodeDeploy will shift traffic for (e.g., prod traffic)
          # Optional: Define hooks for pre-traffic and post-traffic validation Lambdas here
          # Hooks:
          #   PreTrafficHook: !GetAtt PreTrafficValidationLambda.Arn # Reference a Lambda ARN
          #   PostTrafficHook: !GetAtt PostTrafficValidationLambda.Arn # Reference a Lambda ARN

      # Auto-rollback settings
      AutoRollbackConfiguration:
        Enabled: true
        Events:
          - DEPLOYMENT_FAILURE # Rollback on deployment failure
          # - DEPLOYMENT_STOP_ON_ALARM # Can integrate with CloudWatch alarms for health monitoring
          # - DEPLOYMENT_STOP_ON_REQUEST # Manual rollback

      # Add tags to the deployment group
      Tags:
        - Key: Project
          Value: TransactionSimulator
        - Key: Environment
          Value: Production # This deployment group manages the production LIVE alias
