AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Instances for Staging and Production with CodeDeploy agent (Ubuntu AMI).

Parameters:
  LatestAmiId:
    Type: String
    Default: 'ami-0a7d80731ae1b2435' # IMPORTANT: Ensure this is a current Ubuntu 22.04 LTS AMI ID for us-east-1
    Description: Latest Ubuntu Server 22.04 LTS AMI ID for us-east-1.
  KeyPairName:
    Type: String
    Description: The name of an existing EC2 KeyPair to enable SSH access to the instances.
    Default: 'DevSecOpsPipeline' # IMPORTANT: Replace with your actual key pair name

Resources:
  # Security Group to allow HTTP, SSH, AND PORT 3000 access
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: DevSecOpsWebServerSG
      GroupDescription: Enable HTTP, SSH, and Node.js app (port 3000) access
      VpcId: !ImportValue DevSecOpsVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80 # HTTP
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22 # SSH
          ToPort: 22
          CidrIp: 0.0.0.0/0 # Allow SSH from anywhere (restrict in prod)
        - IpProtocol: tcp # NEW RULE: Allow Node.js app port
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0 # Allow from anywhere for demo purpose

  # EC2 Instance for Staging Environment
  StagingEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro # Free Tier eligible
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !ImportValue DevSecOpsEC2CodeDeployProfileName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !Ref WebServerSecurityGroup
          SubnetId: !ImportValue DevSecOpsPublicSubnetId
      Tags:
        - Key: Name
          Value: DevSecOps-Staging-Instance
        - Key: Environment
          Value: Staging
        - Key: Project
          Value: DevSecOpsDemo
      UserData: !Base64 |
        #!/bin/bash
        sudo apt update -y
        sudo apt install -y ruby-full wget git apt-transport-https ca-certificates curl gnupg lsb-release

        curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
        sudo apt-get install -y nodejs
        echo "Node.js installed."

        sudo npm install -g pm2
        echo "PM2 installed."

        cd /home/ubuntu
        wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install
        chmod +x ./install
        sudo ./install auto
        sudo service codedeploy-agent start
        echo "CodeDeploy Agent installed and started."

        sudo mkdir -p /home/ubuntu/devsecops-app
        sudo chown -R ubuntu:ubuntu /home/ubuntu/devsecops-app
        echo "Permissions set for /home/ubuntu/devsecops-app."

  # EC2 Instance for Production Environment
  ProductionEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro # Free Tier eligible
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !ImportValue DevSecOpsEC2CodeDeployProfileName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !Ref WebServerSecurityGroup
          SubnetId: !ImportValue DevSecOpsPublicSubnetId
      Tags:
        - Key: Name
          Value: DevSecOps-Production-Instance
        - Key: Environment
          Value: Production
        - Key: Project
          Value: DevSecOpsDemo
      UserData: !Base64 |
        #!/bin/bash
        sudo apt update -y
        sudo apt install -y ruby-full wget git apt-transport-https ca-certificates curl gnupg lsb-release

        curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
        sudo apt-get install -y nodejs
        echo "Node.js installed."

        sudo npm install -g pm2
        echo "PM2 installed."

        cd /home/ubuntu
        wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install
        chmod +x ./install
        sudo ./install auto
        sudo service codedeploy-agent start
        echo "CodeDeploy Agent installed and started."

        sudo mkdir -p /home/ubuntu/devsecops-app
        sudo chown -R ubuntu:ubuntu /home/ubuntu/devsecops-app
        echo "Permissions set for /home/ubuntu/devsecops-app."

Outputs: # <--- This Outputs block must be at the top level, outside of Resources
  StagingInstancePublicIp:
    Description: Public IP of the Staging EC2 Instance
    Value: !GetAtt StagingEC2Instance.PublicIp
    Export:
      Name: DevSecOpsStagingInstancePublicIp

  ProductionInstancePublicIp:
    Description: Public IP of the Production EC2 Instance
    Value: !GetAtt ProductionEC2Instance.PublicIp
    Export:
      Name: DevSecOpsProductionInstancePublicIp

  WebServerSecurityGroup:
    Description: Security Group ID for web servers
    Value: !Ref WebServerSecurityGroup
    Export:
      Name: DevSecOpsWebServerSecurityGroup