AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Roles for DevSecOps Pipeline using CodePipeline, CodeBuild, CodeDeploy, and EC2. (V7 - Exporting All Required Role/Topic ARNs)

Resources:
  # IAM Role for AWS CodePipeline
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DevSecOpsCodePipelineServiceRoleV2
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodePipeline_FullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AWSCodeDeployFullAccess
      Path: /

  # IAM Role for AWS CodeBuild
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DevSecOpsCodeBuildServiceRoleV2
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Path: /

  # IAM Role for AWS CodeDeploy
  CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DevSecOpsCodeDeployServiceRoleV2
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess # Keeping AdministratorAccess for now
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Path: /

  # IAM Role for EC2 Instances (for CodeDeploy Agent)
  EC2InstanceProfileRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DevSecOpsEC2CodeDeployRoleV2
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess # Keeping AdministratorAccess for now
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Path: /

  # IAM Instance Profile for EC2 Instances
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: DevSecOpsEC2CodeDeployProfileV2
      Roles:
        - !Ref EC2InstanceProfileRole

  # SNS Topic for Manual Approval notifications
  DevSecOpsApprovalNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: DevSecOpsApprovalNotificationV2
      DisplayName: DevSecOps Approval Notifications V2

Outputs:
  # Export the ARN of the CodePipeline Service Role
  CodePipelineServiceRoleArn:
    Description: ARN of the CodePipeline Service Role
    Value: !GetAtt CodePipelineServiceRole.Arn
    Export:
      Name: DevSecOpsCodePipelineServiceRoleV2Arn # <--- NEW EXPORT

  # Export the ARN of the CodeBuild Service Role
  CodeBuildServiceRoleArn:
    Description: ARN of the CodeBuild Service Role
    Value: !GetAtt CodeBuildServiceRole.Arn
    Export:
      Name: DevSecOpsCodeBuildServiceRoleV2Arn # <--- NEW EXPORT

  # Export the ARN of the CodeDeploy Service Role
  CodeDeployServiceRoleArn:
    Description: ARN of the CodeDeploy Service Role
    Value: !GetAtt CodeDeployServiceRole.Arn
    Export:
      Name: DevSecOpsCodeDeployServiceRoleV2Arn

  # Export the ARN of the EC2 Instance Profile
  EC2InstanceProfileArn:
    Description: ARN of the EC2 Instance Profile for CodeDeploy agent
    Value: !GetAtt EC2InstanceProfile.Arn
    Export:
      Name: DevSecOpsEC2CodeDeployProfileV2Arn

  # Export the NAME of the EC2 Instance Profile (for use with EC2::Instance)
  EC2InstanceProfileName:
    Description: Name of the EC2 Instance Profile for CodeDeploy agent
    Value: !Ref EC2InstanceProfile
    Export:
      Name: DevSecOpsEC2CodeDeployProfileNameV2

  # Export the ARN of the SNS Topic
  DevSecOpsApprovalNotificationTopicArn:
    Description: ARN of the SNS Topic for approval notifications
    Value: !Ref DevSecOpsApprovalNotificationTopic # Use !Ref for the ARN of an SNS Topic
    Export:
      Name: DevSecOpsApprovalNotificationTopicV2Arn # <--- NEW EXPORT